### PR TITLE
Elasticsearch: 406 error without specifying content-type #71

### LINKED ISSUE #71: Elasticsearch: 406 error without specifying content-type
Data kit got 406 error on elasticsearch 6+ queries. Reason: `content-type: application/json` header must be set since ES6

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The msearch request must be terminated by a newline [\n]"}],"type":"illegal_arg
ument_exception","reason":"The msearch request must be terminated by a newline [\n]"},"status":400}
```

### PR DESCRIPTION
**Pull request by amper43**
fixes #71 

## Changes

- added optional field `headers`  to `MetricQuery` that will be merged with base headers from `grafana_service` (only authorization now)

### CODE REVIEW

File: src/metrics/elasticsearch_metric.ts [hunk 1]
```diff
@@ -35,7 +35,8 @@ export class ElasticsearchMetric extends AbstractMetric {
     return {
       url: this.datasource.url,
       method: 'POST',
-      schema: { data }
+      schema: { data },
+      headers: {'Content-Type': `application/json;charset=UTF-8`}
```
Comment (rozetko) [inline src/metrics/elasticsearch_metric.ts]: Let's test without this strange charset setting
```suggestion
      headers: {'Content-Type': 'application/json'}
```

**Comment by rozetko** [comment]
Works with 2.4.6
