### PR TITLE
Elasticsearch: Request failed with status code 400 #72

### LINKED ISSUE #72: Elasticsearch: Request failed with status code 400
Data kit got 400 error for elasticsearch 6+. Reason: missing new line in the end of query.

### PR DESCRIPTION
**Pull request by amper43**
fixes #72 

## Changes

- added missed newline

### CODE REVIEW

File: src/metrics/elasticsearch_metric.ts [hunk 1]
```diff
@@ -30,7 +30,8 @@ export class ElasticsearchMetric extends AbstractMetric {
       max: to.toString()
     });
 
-    data = data.map(d => JSON.stringify(d)).join('\n');
+    data = data.filter(d => d !== '').map(d => JSON.stringify(d)).join('\n');
```
Comment (rozetko) [inline src/metrics/elasticsearch_metric.ts]:
```suggestion
    data = data
      .filter(d => d !== '')
      .map(d => JSON.stringify(d)).join('\n');
```

**Comment by rozetko** [comment]
We should also test if it works with ES version less than 6

**Comment by rozetko** [comment]
Works with 2.4.6
