### PR TITLE
Check if there is request result #57

### LINKED ISSUE #57: Check if there is request result
Even if url is wrong, we're trying to handle response from it
There could be no response though
Thus, you get this error:
https://github.com/hastic/hastic-grafana-app/issues/186
It would be better to throw a proper error
e.g. `Please check if Grafana is accessible via http://localhost:3000`

### PR DESCRIPTION
**Pull request by amper43**
fixes #57

### CODE REVIEW

File: src/grafana_service.ts [hunk 1]
```diff
@@ -54,10 +56,17 @@ async function queryGrafana(query: MetricQuery, apiKey: string) {
...
+      if(e.response.status === 401) {
+        console.log(`Data kit: got response ${e.response.status}, message: ${e.message}`);
+        throw new Error('Unauthorized. Check the API_KEY.');
+      }
+    } else {
+      if(e.errno === 'ECONNREFUSED') {
+        throw new ConnectionRefused(e.message);
+      }
     }
+    console.log(`Data kit: got response ${e.response ? e.response.status : e.response}, message: ${e.message}`);
```
Comment (rozetko) [inline src/grafana_service.ts]:
```suggestion
    console.error(`Data kit: got response ${e.response ? e.response.status : e.response}, message: ${e.message}`);
```
